### ISSUE TITLE
Update JS code snippets to use ES2015

### ISSUE THREAD

**Issue by GA-MEB** [ga-wdi-boston/ember-object#4]
Replacing `var` with `let` and `const`, primarily.

**Comment by jrhorn424** [comment]
Also, use arrow functions where they make sense. Remember, they change `this` to lexical scope, so it can break things. I'm still figuring this out. I usually try an arrow function, and if I get an error, try a normal function.

**Comment by GA-MEB** [comment]
It should be noted (though not necessarily in the repo itself) that this requires Chrome 49+ or Microsoft Edge 14+. Firefox doesn't fully support `let` or `const` yet on any version.

http://kangax.github.io/compat-table/es6/

**Comment by GA-MEB** [comment]
Doing this has introduced a new issue - running scripts by pasting them into the console is awkward. We should try to find a better way to handle this.
